# Generated by Django 4.1.3 on 2022-12-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.TextField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Question',
            new_name='question',
        ),
    ]
