# Generated by Django 4.1.3 on 2022-12-13 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('example', '0003_lang_rename_answer_question_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=200)),
                ('Answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='lang',
            field=models.ForeignKey(default='Spanish', on_delete=django.db.models.deletion.CASCADE, to='example.lang'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.TextField(max_length=500)),
                ('wrong_answers', models.TextField(max_length=500)),
                ('difficulty', models.IntegerField()),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.lang')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
