"""
Django settings for djangotemplates project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path, os

# Build paths inside the project like this: BASE_DIR / 'subdir'.                                                                                                                                                
BASE_DIR = Path(__file__).resolve().parent.parent # The base directory equals the path + file and any parents of it

LOGIN_REDIRECT_URL = '/index' #When logged in the user will be redirected to the main website name (in our case localhost:8000) then with the added /index 

LOGIN_URL = '/login_user'

LOGOUT_REDIRECT_URL = '/login_user' #When logged out the user will be redirected to the login page with '/login_user' being concatinated                                                        

# Quick-start development settings - unsuitable for production                                                                                                          
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/                                                                         

# SECURITY WARNING: keep the secret key used in production secret!                                                                          
SECRET_KEY = 'django-insecure-66t-&j+jn$@&qf-02j(l99c1t=vmthbjs(5ogg5*lg)khns*a('                                                                   

# SECURITY WARNING: don't run with debug turned on in production!                                           
DEBUG = True

ALLOWED_HOSTS = []                                                               


# Application definition. These are our installed apps in our django app

INSTALLED_APPS = [ 
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'example',
]
#Middleware is the software and applications that provide serices to the program. These can be security and authentication for example
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangotemplates.urls' 
#This controls the django templates such as swhere they are in the directory and the backend connections
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
#WSGI for Django. WSGI stands for web server gateway interface and is used for calling webserver forward requests.
WSGI_APPLICATION = 'djangotemplates.wsgi.application'


# Database. 
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': { #Its a default database
        'ENGINE': 'django.db.backends.mysql', #The database engine I used for my project is MySQL
        'NAME': 'questionsdb', #The database name
        'USER': 'root', #The database user I defined 
        'PASSWORD': '1515', #The password for access to the database. It is a local one currently so this does not need to be encrypted as its not sent to the server 
        'HOST': 'localhost', # Stored locally
        'PORT': '3307', #The port 
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/' #For static URLs the URL static/ will be defined 

# Add these new lines
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
# The static file path is joined to the base diretory 
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ASGI_APPLICATION = "djangotemplates.asgi.application"
#For the ASGI application and channels the backend is configured using the Redis in-memory data store. 
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)], #The loopback adresss IP and the Redis TCP host
        },
    },
}




